const selectors = {
  mainWrapper: `main[role="main"]`,
  mainColumn: `[data-testid="primaryColumn"]`,
  topHeader: `[data-testid="primaryColumn"] > div > div:nth-of-type(1)`,
  leftSidebar: `header[role="banner"]`,
  leftSidebarLinks: `header[role="banner"] nav[role="navigation"]`,
  leftSidebarUnreadBadge: `header[role="banner"] nav[role="navigation"] a svg + div[aria-label]:only-of-type`,
  sidebarLinks: {
    logo: `header[role="banner"] div:first-child > div:first-child div:first-child > div:first-child > h1:only-child[role="heading"]`,
    home: `header[role="banner"] [data-testid="AppTabBar_Home_Link"]`,
    explore: `header[role="banner"] [data-testid="AppTabBar_Explore_Link"]`,
    notifications: `header[role="banner"] [data-testid="AppTabBar_Notifications_Link"]`,
    messages: `header[role="banner"] [data-testid="AppTabBar_DirectMessage_Link"]`,
    bookmarks: `header[role="banner"] a[href*="bookmarks"], header[role="banner"] a[href*="history"]`,
    jobs: `header[role="banner"] a[href*="jobs"]`,
    articles: 'a[href="/compose/articles"]',
    topics: 'header[role="banner"] a[href*=topics]',
    circles: 'header[role="banner"] a[href*=circles]',
    communities: 'header[role="banner"] a[href*=communities]',
    profile: `header[role="banner"] [data-testid="AppTabBar_Profile_Link"]`,
    lists: `header[role="banner"] a[href*="lists"][role="link"][aria-label]`,
    xPremium: `header[role="banner"] a[href*="premium"][role="link"][aria-label]`,
    verifiedOrgs: `header[role="banner"] a[href*="verified-orgs"][role="link"][aria-label]`,
    analytics: `header[role="banner"] .xf-sidebar-button[aria-label="Analytics"]`,
    grok: `header[role="banner"] a[href*="grok"][role="link"][aria-label]`,
    creatorStudio: `header[role="banner"] a[href*="creators/studio"]`,
    moreMenu: `header[role="banner"] [data-testid="AppTabBar_More_Menu"]`,
  },
  accountSwitcherButton: `[data-testid="SideNav_AccountSwitcher_Button"]`,
  leftSidebarLabel: `header[role="banner"] nav[role="navigation"] > *:not([data-testid="SideNav_NewTweet_Button"]) > div > div + div:last-child`,
  accountSwitcherLabel: `[data-testid="SideNav_AccountSwitcher_Button"] > div:not(:first-child)`,
  leftSidebarLabel_hover: `header[role="banner"] nav[role="navigation"]:hover > *:not([data-testid="SideNav_NewTweet_Button"]) > div > div + div:last-child`,
  accountSwitcherLabel_hover: `[data-testid="SideNav_AccountSwitcher_Button"]:hover > div:not(:first-child)`,
  rightSidebar: `[data-testid="sidebarColumn"]`,
  tweetCounts: `[role="group"][id*="id__"]:only-child`,
  viewCount: `[role="group"][id*="id__"]:only-child a[href*='/analytics']`,
  tweet: `[data-testid="tweet"][role="article"]`,
  tweetSpan: `[data-testid="tweet"][role="article"] div > div:only-child > span:only-child > span`,
  modalExternalWrapper: `div[role="group"]`,
  modalBackground: `div[role="group"] > div:empty`,
  modalWrapper: `div[aria-labelledby="modal-header"][role="dialog"]`,
  modalUi: `div[aria-labelledby="modal-header"][role="dialog"] > div`,
  tweetButton: `a[data-testid="SideNav_NewTweet_Button"]`,
  securityAndAccountAccess: `[data-testid="accountAccessScreen"]`,
}

export default selectors
